// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxzlC6-ug_LNN9qNEVh3UFy2uBxfOhpY4',
    appId: '1:856846965176:web:ce7181289256da6622174d',
    messagingSenderId: '856846965176',
    projectId: 'shin-spotify',
    authDomain: 'shin-spotify.firebaseapp.com',
    storageBucket: 'shin-spotify.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv54UwK9pR1JjF2LyIA1X6CpX838rqUnM',
    appId: '1:856846965176:android:4d6cef05f344c0e222174d',
    messagingSenderId: '856846965176',
    projectId: 'shin-spotify',
    storageBucket: 'shin-spotify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALHqQRaCgr4mBT0jS8qxBCwYKyrLe8EZE',
    appId: '1:856846965176:ios:766bdd6f5fda33ca22174d',
    messagingSenderId: '856846965176',
    projectId: 'shin-spotify',
    storageBucket: 'shin-spotify.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxzlC6-ug_LNN9qNEVh3UFy2uBxfOhpY4',
    appId: '1:856846965176:web:20578b452f7a677722174d',
    messagingSenderId: '856846965176',
    projectId: 'shin-spotify',
    authDomain: 'shin-spotify.firebaseapp.com',
    storageBucket: 'shin-spotify.firebasestorage.app',
  );
}
